#!/bin/bash

# ----------------------------------
# Author: Shuijin Li
# Date: 28 Jun 2023
# Email: skli@dundee.ac.uk
# Version: 1.1
# Purpose:
# This script is used to extract forces and moments data from the "forces.dat" 
# file generated by OpenFOAM simulations, split it into pressure, viscous and porous
# components, and save the data to separate files for further analysis. It also ensures 
# that only the last occurrence of each time step is kept if there are duplicates.
# 
# Input: 
# - "forces.dat" file containing forces and moments data.
#
# Output:
# - Time vs forces and moments files for each of pressure, viscous, and porous components.
#   These files are named in the format "t_vs_forces_TYPE.txt" and "t_vs_moments_TYPE.txt",
#   where TYPE can be either "pressure", "viscous", or "porous".
# ----------------------------------

# File path
FILE_PATH="forces.dat"

# Output directory
OUT_DIR_PATH="."

# Extract the time, forces and moments data from the file
extract_data() {
    echo "Extracting data..."

    # Remove the first three lines (header)
    temp_file="${FILE_PATH}.tmp"
    tail -n +4 "$FILE_PATH" > "$temp_file"

    # Extract time and save to a temp file, keeping only the last occurrence of each time step
    awk '!x[$1]++' "$temp_file" > "${temp_file}_no_duplicates"
    
    # Extract time
    awk '{print $1}' "${temp_file}_no_duplicates" > "$OUT_DIR_PATH/temp_times.txt"
    
    local forces=("2" "3" "4" "5" "6" "7" "8" "9" "10")
    local moments=("11" "12" "13" "14" "15" "16" "17" "18" "19")
    local types=("pressure" "viscous" "porous")
    
    for index in 0 1 2; do
        type=${types[$index]}
        
        # Extract forces data
        awk -v f1="${forces[3*index]}" -v f2="${forces[3*index+1]}" -v f3="${forces[3*index+2]}" '{gsub(/[\(\)]/, "", $f1); gsub(/[\(\)]/, "", $f2); gsub(/[\(\)]/, "", $f3); print $f1, $f2, $f3}' "${temp_file}_no_duplicates" > "$OUT_DIR_PATH/temp_forces_${type}.txt"
        
        # Extract moments data
        awk -v m1="${moments[3*index]}" -v m2="${moments[3*index+1]}" -v m3="${moments[3*index+2]}" '{gsub(/[\(\)]/, "", $m1); gsub(/[\(\)]/, "", $m2); gsub(/[\(\)]/, "", $m3); print $m1, $m2, $m3}' "${temp_file}_no_duplicates" > "$OUT_DIR_PATH/temp_moments_${type}.txt"
    done

    # Remove temporary files
    rm "$temp_file"
    rm "${temp_file}_no_duplicates"
}

paste_data() {
    # Paste times and forces/moments into separate files
    local types=("pressure" "viscous" "porous")
    for type in "${types[@]}"; do
        echo "Saving time-series file of $type forces ..."
        paste "$OUT_DIR_PATH/temp_times.txt" "$OUT_DIR_PATH/temp_forces_${type}.txt" > "$OUT_DIR_PATH/t_vs_forces_${type}.txt"
        
        echo "Saving time-series file of $type moments ..."
        paste "$OUT_DIR_PATH/temp_times.txt" "$OUT_DIR_PATH/temp_moments_${type}.txt" > "$OUT_DIR_PATH/t_vs_moments_${type}.txt"
    done
}

# Call the functions
extract_data
paste_data
